#!/bin/bash

set -eo pipefail

export ETCD_PORT=${ETCD_PORT:-4001}
export HOST_IP=${HOST_IP:-172.17.8.101}
export ETCD=$HOST_IP:$ETCD_PORT

until confd -onetime -node $ETCD -config-file /etc/confd/conf.d/haproxy.toml; do
  echo "[haproxy] waiting for confd to create initial confd configuration"
  sleep 5
done

confd -interval 10 -node $ETCD -config-file /etc/confd/conf.d/haproxy.toml &
echo "[haproxy] confd is now monitoring etcd for changes..."

# Follow the logs to allow the script to continue running
tail -f /etc/confd/conf.d/haproxy.toml

